
export const SOME_ACTION = "SOME_ACTION";
export const LOAD_DB_TO_STORE = "LOAD_DB_TO_STORE";
export const CHANGE_CURRENT_QUESTION = "CHANGE_CURRENT_QUESTION";
export const CHECK_CURRENT_QUESTION = "CHECK_CURRENT_QUESTION";
