
export const SOME_ACTION = "SOME_ACTION";
export const LOAD_DB_TO_STORE = "LOAD_DB_TO_STORE";
export const CHANGE_CURRENT_QUESTION = "CHANGE_CURRENT_QUESTION";
export const CHECK_CURRENT_QUESTION = "CHECK_CURRENT_QUESTION";
export const ADD_PLAYER = "ADD_PLAYER";
export const UPDATE_STORE = "UPDATE_STORE";
export const CHANGE_AVERAGE = "CHANGE_AVERAGE";
export const ADD_QUESTION = "ADD_QUESTION";

export const USER_AUTHORIZATION = "USER_AUTHORIZATION";
export const RESET_CARDS = "RESET_CARDS";
export const FLIP_CARDS = "FLIP_CARDS";
export const SAVE_ANSWER = "SAVE_ANSWER";

export const GET_USERPIC = 'GET_USERPIC';
